### ISSUE TITLE
Ship detection and speed

### ISSUE THREAD

**Issue by Gorgarn** [zAlweNy26/AlweStats#1]
Two screenshots, 
First one, I'm on land not even targeting the longboat, Issue there is longboat health is showing.
The second issue ship speed is off by at least 100. 
![2022-02-24-1345](https://user-images.githubusercontent.com/39360130/155589390-b73032bc-40af-4329-937a-f3729fd81f1e.png)
![2022-02-24-1340](https://user-images.githubusercontent.com/39360130/155589388-debb5c50-cb4a-4d49-a68a-615634ef9d48.png)

**Comment by zAlweNy26** [comment]
In the first screenshot, how did you get off the ship? Did something abnormal happen that caused this?
For the second screenshot, you are on the ship but it shows 0 kts, but what situation were you in?

**Comment by Gorgarn** [comment]
The order of the screenshots reverse when I uploaded them. the dark background was taken from the shore looking at the longboat, the light background screenshot, I was at the helm of the longboat
![2022-02-24-1338](https://user-images.githubusercontent.com/39360130/155713239-4c3b47fc-a12d-4d05-97b2-1a09125ec4cc.png)

seems I did not keep a full capture when I was at the helm..

**Comment by zAlweNy26** [comment]
I think I fixed this issue, try using the new version uploaded to Thunderstore.
