### ISSUE TITLE
Error Spam when on building mode

### ISSUE THREAD

**Issue by codewithbjim** [zAlweNy26/AlweStats#10]
![image](https://user-images.githubusercontent.com/19782129/157395529-d6f3f0cb-ed94-449c-b5fe-2e5c802fef88.png)

The error above is spamming the console non-stop while placing building pieces

**Comment by zAlweNy26** [comment]
Yeah I kinda fixed this but I'm working on other features before publishing the new patch

**Comment by codewithbjim** [comment]
Cool, I'll close this one once the patch is out!

**Comment by zAlweNy26** [comment]
Check it out on Thunderstore and let me know if you find any issues !
