### ISSUE TITLE
Huge performance hit

### ISSUE THREAD

**Issue by brianmiller** [zAlweNy26/AlweStats#11]
It looks like AlweStats is killing performance and we had to remove it from all worlds.  Maybe a frequent polling issue?

Before AlweStats: (65-180FPS)
![image](https://user-images.githubusercontent.com/342276/160006016-5a96f141-ec4a-4d0a-af44-ddcea63363ef.png)

After AlweStats: (20-30FPS)
![image](https://user-images.githubusercontent.com/342276/160006128-41342031-85a3-4a65-8b47-6c913f516531.png)

**Comment by zAlweNy26** [comment]
Yeah, I'm so sorry for this, if you disable all the MapStats config settings it should be working fine. I'll try to fix it as soon as possible.

**Comment by brianmiller** [comment]
No problem! We love the mod.  Thank you for the hard work!

**Comment by zAlweNy26** [comment]
Please check the new version out on ThunderStore, I tried my best to reduce the load on the performance. Let me know if you see any changes!

**Comment by zAlweNy26** [comment]
I mark this as solved for no response. Feel free to open it again if you still have performance issues.

**Comment by brianmiller** [comment]
> I mark this as solved for no response. Feel free to open it again if you still have performance issues.

I missed the updates. Apologies for not replying.  We'll give it a shot today.

**Comment by zAlweNy26** [comment]
No problem, let me know if it's all ok !

**Comment by brianmiller** [comment]
> No problem, let me know if it's all ok !

Performance is much better.  We'll give it a good test (5-6 hrs) on Friday.

Thank you for the fix.  What was the issue? Any concern from you that there's still a performance hit?

-Brian

**Comment by zAlweNy26** [comment]
The problem was related to the continuous scanning of elements in the map and mostly linked to the explored percentage that was using big sized arrays every single second, causing a lowering of fps. 

I tried to increase the performance as much as I could, reducing the requests by patching different methods instead of the previous ones that were causing lag.

**Comment by brianmiller** [comment]
Your changes certainly helped, but there's still a significant performance hit.  Like-for-like tests are showing an average of 28-35fps with AlweStats enabled and 45-70 without.

-Brian

**Comment by zAlweNy26** [comment]
Really?? I don't know how to improve the performance more than this, I tested it personally and I don't see that huge performance hit. My FPS go from 95 without to 80 with it. Try disable everything in the MapStats section and let me know if it's better.
