### ISSUE TITLE
Do you cache portal positions?

### ISSUE THREAD

**Issue by 4Magma** [zAlweNy26/AlweStats#13]
Hi,

i had a situation where the portal arrow pointed to a empty position
- 2 portals: 1 in near in north, 1 far in south-west
- but arrow pointed to position in south, where i found only forest
- play with my old char on a new map (20d+)

**Comment by zAlweNy26** [comment]
Yes I cache the portal positions once it scans all the map on the load of the world. This bug occurred when you destroyed the portal or in others situations?

**Comment by 4Magma** [comment]
No, there was nothing before! I think its a something from the old world i played.

**Comment by zAlweNy26** [comment]
Maybe there was a portal of some kind and the game didn't remove it.

**Comment by 4Magma** [comment]
Gone back to my old world:
- at position -203, -666 is also nothing
- but all your map pins have yellow circles (not in new world)

I think its the same as the ping during login.
I removed Auto Map Pin mod, because of massive lags through it.
The new world is created without AMP, while the old was with.

i was in a similar situation before:
- in my old map, before creating the new map
- followed the coast line of my island on a raft from ValheimRaft
- it had only a steer, a workbench, and a portal on board
- at some moment during the voyage, the yellow ping symbol started to follow the position of the raft/portal

**Comment by zAlweNy26** [comment]
Can you make a screenshot of what you are saying?

**Comment by 4Magma** [comment]
![20220330155628_1](https://user-images.githubusercontent.com/17728444/160852956-9f93f388-f63b-4318-acc5-9db6a189e830.jpg)
old world with a lot yellow framed pins
- some are some not
- i'm sure is not related to already visited, since some i was but the swamp crypts definitive not

![20220330115603_1](https://user-images.githubusercontent.com/17728444/160852971-c96c8d9d-e242-4661-9cfd-d73828cc47e9.jpg)
new world map 
- base 1 is north from my position
- base 2 is south west below trader
- wrong teleporter is south of my position

![20220330115913_1](https://user-images.githubusercontent.com/17728444/160852970-b07d7b98-711c-4279-ab8b-34c4a002423f.jpg)
empty place where arrow points at

**Comment by zAlweNy26** [comment]
In the first image, it was already like that the first time you joined with AlweStats activated or from the second join and so on?

For the second and third image, have you ever encountered in any world, a stone portal? There this type of portal that I added but maybe I am wrong and I should only check for wood portals

**Comment by 4Magma** [comment]
- i saw the yellow circles the first time today as i gone back to check the portal position
  - think is related to removing Auto Map Pin
  - https://www.nexusmods.com/valheim/mods/744
  - dropped because same problems as described in 1. bug in Nexus
  - was first time after dropping AMP to return to this world

no, until now i saw only the buildable version

**Comment by zAlweNy26** [comment]
Ok yes it was because you removed Auto Map Pins.

So I think maybe I should remove the stone portals from the list... I found them as items and thought it was a stone version of the portal but maybe it is just a portal construction for dungeons.
