### ISSUE TITLE
Error FormatException 

### ISSUE THREAD

**Issue by 4Magma** [zAlweNy26/AlweStats#15]
[alwe_error.txt](https://github.com/zAlweNy26/AlweStats/files/8410486/alwe_error.txt)

log is flooded with following errors (addresses replaced with ####)

A
[Error  : Unity Log] FormatException: Input string was not in a correct format.
Stack trace:
System.Number.StringToNumber (System.String str, System.Globalization.NumberStyles options, System.Number+NumberBuffer& number, System.Globalization.NumberFormatInfo info, System.Boolean parseDecimal) (at <####>:0)
System.Number.ParseInt32 (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <####>:0)
System.Int32.Parse (System.String s) (at <####>:0)
System.Array.ConvertAll[TInput,TOutput] (TInput[] array, System.Converter`2[TInput,TOutput] converter) (at <####>:0)
AlweStats.Utilities.CheckInEnum[T] (T type, System.String setting) (at <####>:0)
AlweStats.MapStats.PatchAddPin (Minimap __instance, Minimap+PinData& __result, UnityEngine.Vector3 pos, Minimap+PinType& type, System.String& name, System.Boolean save, System.Boolean isChecked, System.Int64 ownerID) (at <####>:0)
(wrapper dynamic-method) Minimap.DMD<Minimap::AddPin>(Minimap,UnityEngine.Vector3,Minimap/PinType,string,bool,bool,long)
Minimap.SetMapData (System.Byte[] data) (at <####>:0)
(wrapper dynamic-method) Minimap.DMD<Minimap::LoadMapData>(Minimap)
(wrapper dynamic-method) Minimap.DMD<Minimap::Update>(Minimap)

B
[Error  : Unity Log] FormatException: Input string was not in a correct format.
Stack trace:
System.Number.StringToNumber (System.String str, System.Globalization.NumberStyles options, System.Number+NumberBuffer& number, System.Globalization.NumberFormatInfo info, System.Boolean parseDecimal) (at <####>:0)
System.Number.ParseInt32 (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <####>:0)
System.Int32.Parse (System.String s) (at <####>:0)
System.Array.ConvertAll[TInput,TOutput] (TInput[] array, System.Converter`2[TInput,TOutput] converter) (at <####>:0)
AlweStats.Utilities.CheckInEnum[T] (T type, System.String setting) (at <####>:0)
AlweStats.MapStats.PatchAddPin (Minimap __instance, Minimap+PinData& __result, UnityEngine.Vector3 pos, Minimap+PinType& type, System.String& name, System.Boolean save, System.Boolean isChecked, System.Int64 ownerID) (at <####>:0)
(wrapper dynamic-method) Minimap.DMD<Minimap::AddPin>(Minimap,UnityEngine.Vector3,Minimap/PinType,string,bool,bool,long)
AlweStats.MapStats.SetElementPin (Minimap map, ZDO zdo) (at <####>:0)
AlweStats.MapStats.LoadZDOs () (at <####>:0)
AlweStats.MapStats.PatchCreateZDO (ZNetScene __instance, ZDO zdo) (at <####>:0)
(wrapper dynamic-method) ZNetScene.DMD<ZNetScene::AddInstance>(ZNetScene,ZDO,ZNetView)
(wrapper dynamic-method) ZNetView.DMD<ZNetView::Awake>(ZNetView)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
ZNetScene:CreateObject(ZDO)
ZNetScene:CreateDistantObjects(List`1, Int32, Int32&)
ZNetScene:CreateObjects(List`1, List`1)
ZNetScene:DMD<ZNetScene::CreateDestroyObjects>(ZNetScene)
ZNetScene:DMD<ZNetScene::Update>(ZNetScene)

C
[Error  : Unity Log] FormatException: Input string was not in a correct format.
Stack trace:
System.Number.StringToNumber (System.String str, System.Globalization.NumberStyles options, System.Number+NumberBuffer& number, System.Globalization.NumberFormatInfo info, System.Boolean parseDecimal) (at <####>:0)
System.Number.ParseInt32 (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <####>:0)
System.Int32.Parse (System.String s) (at <####>:0)
System.Array.ConvertAll[TInput,TOutput] (TInput[] array, System.Converter`2[TInput,TOutput] converter) (at <####>:0)
AlweStats.Utilities.CheckInEnum[T] (T type, System.String setting) (at <####>:0)
AlweStats.MapStats.PatchAddPin (Minimap __instance, Minimap+PinData& __result, UnityEngine.Vector3 pos, Minimap+PinType& type, System.String& name, System.Boolean save, System.Boolean isChecked, System.Int64 ownerID) (at <####>:0)
(wrapper dynamic-method) Minimap.DMD<Minimap::AddPin>(Minimap,UnityEngine.Vector3,Minimap/PinType,string,bool,bool,long)
AlweStats.MapStats.SetElementPin (Minimap map, ZDO zdo) (at <####>:0)
AlweStats.MapStats.PatchCreateZDO (ZNetScene __instance, ZDO zdo) (at <####>:0)
(wrapper dynamic-method) ZNetScene.DMD<ZNetScene::AddInstance>(ZNetScene,ZDO,ZNetView)
(wrapper dynamic-method) ZNetView.DMD<ZNetView::Awake>(ZNetView)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
ZNetScene:CreateObject(ZDO)
ZNetScene:CreateObjectsSorted(List`1, Int32, Int32&)
ZNetScene:CreateObjects(List`1, List`1)
ZNetScene:DMD<ZNetScene::CreateDestroyObjects>(ZNetScene)
ZNetScene:DMD<ZNetScene::Update>(ZNetScene)

D
[Error  : Unity Log] FormatException: Input string was not in a correct format.
Stack trace:
System.Number.StringToNumber (System.String str, System.Globalization.NumberStyles options, System.Number+NumberBuffer& number, System.Globalization.NumberFormatInfo info, System.Boolean parseDecimal) (at <####>:0)
System.Number.ParseInt32 (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <####>:0)
System.Int32.Parse (System.String s) (at <####>:0)
System.Array.ConvertAll[TInput,TOutput] (TInput[] array, System.Converter`2[TInput,TOutput] converter) (at <####>:0)
AlweStats.Utilities.CheckInEnum[T] (T type, System.String setting) (at <####>:0)
AlweStats.MapStats.PatchAddPin (Minimap __instance, Minimap+PinData& __result, UnityEngine.Vector3 pos, Minimap+PinType& type, System.String& name, System.Boolean save, System.Boolean isChecked, System.Int64 ownerID) (at <####>:0)
(wrapper dynamic-method) Minimap.DMD<Minimap::AddPin>(Minimap,UnityEngine.Vector3,Minimap/PinType,string,bool,bool,long)
AlweStats.MapStats.LoadLocations () (at <####>:0)
AlweStats.MapStats.ShowDungeonsPins (Location __instance) (at <####>:0)
(wrapper dynamic-method) Location.DMD<Location::Awake>(Location)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
ZoneSystem:SpawnLocation(ZoneLocation, Int32, Vector3, Quaternion, SpawnMode, List`1)
ZoneSystem:SpawnProxyLocation(Int32, Int32, Vector3, Quaternion)
LocationProxy:SpawnLocation()
LocationProxy:Awake()
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
ZNetScene:CreateObject(ZDO)
ZNetScene:CreateObjectsSorted(List`1, Int32, Int32&)
ZNetScene:CreateObjects(List`1, List`1)
ZNetScene:DMD<ZNetScene::CreateDestroyObjects>(ZNetScene)
ZNetScene:DMD<ZNetScene::Update>(ZNetScene)

E
[Error  : Unity Log] FormatException: Input string was not in a correct format.
Stack trace:
System.Number.StringToNumber (System.String str, System.Globalization.NumberStyles options, System.Number+NumberBuffer& number, System.Globalization.NumberFormatInfo info, System.Boolean parseDecimal) (at <####>:0)
System.Number.ParseInt32 (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <####>:0)
System.Int32.Parse (System.String s) (at <####>:0)
System.Array.ConvertAll[TInput,TOutput] (TInput[] array, System.Converter`2[TInput,TOutput] converter) (at <####>:0)
AlweStats.Utilities.CheckInEnum[T] (T type, System.String setting) (at <####>:0)
AlweStats.MapStats.PatchAddPin (Minimap __instance, Minimap+PinData& __result, UnityEngine.Vector3 pos, Minimap+PinType& type, System.String& name, System.Boolean save, System.Boolean isChecked, System.Int64 ownerID) (at <####>:0)
(wrapper dynamic-method) Minimap.DMD<Minimap::AddPin>(Minimap,UnityEngine.Vector3,Minimap/PinType,string,bool,bool,long)
Minimap.SetMapData (System.Byte[] data) (at <####>:0)
(wrapper dynamic-method) Minimap.DMD<Minimap::LoadMapData>(Minimap)
(wrapper dynamic-method) Minimap.DMD<Minimap::Update>(Minimap)

in following order
AA,B,AAAAAAAAAAAAAAAAAAAAAAAAAA,CCC,AA,CC,AA,CC,AAAA,CC,AAAA,CC,A,C,A,CC,AA,CC,A,CCC,A,D,AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,E

- think it's because i moved alwe.stats from plugins/ with dll to AlweStats subdir
- world loading takes ages, screen is full of glowing balls, minimap grey
- game restartet after moving alwe.stats back to plugins
- world loads fast, but log flooded with error messages

**Comment by 4Magma** [comment]
![20220404161833_1](https://user-images.githubusercontent.com/17728444/161572666-eb3ec4bf-fe28-4a53-9fb8-4a27953ba1e6.jpg)

**Comment by zAlweNy26** [comment]
It seems there is some formatting error in the config file AlweStats.cfg. Try deleting it and restart the game.

**Comment by zAlweNy26** [comment]
The Alwe.stats file is no longer used by the mod, so you can delete it.

**Comment by 4Magma** [comment]
Yes, it was the config file

- renamed, game started, with winmerge compared
- orphan lines 
  - EntityDistance = true
  - RockStatus = true
  - TreeStatus = true
  - BushStatus = true
  - PlantStatus = true
  - FermenterStatus = true
  - FireStatus = true
  - BeehiveStatus = true
  - ContainerStatus = true
  - PieceStatus = true
  - ShowCursorCoordinatesInMap = true

**Comment by zAlweNy26** [comment]
I removed these lines in a previous version (3.8.0) and grouped them all in just one (ShowEnvStatus).

**Comment by zAlweNy26** [comment]
Please, read the changelogs before posting issues for errors. I'll close this issue and mark it as solved.
