### ISSUE TITLE
Setting BiggerPins = 0 makes all non Alwe pins supersized

### ISSUE THREAD

**Issue by NumbaOneIsTW** [zAlweNy26/AlweStats#17]
```
## Double or not the size of specific custom pins, separate them with a comma (,)
## 0 = disable for all custom pins
## 1 = troll caves pins
## 2 = crypts pins
## 3 = fire holes pins
## 4 = portals pins
## 5 = ships pins
## 6 = carts pins
## 7 = mountain caves pins
# Setting type: String
# Default value: 4, 5, 6
BiggerPins = 6
```
When BiggerPins is set to 0, all vanilla map pins become double their size. If one or more value(s) is set for BiggerPins, the vanilla pins revert to normal size.

**Comment by zAlweNy26** [comment]
Ok thanks for the warning, I'll check and fix it !

**Comment by zAlweNy26** [comment]
I fixed this, wait for the next patch ✌🏼

**Comment by zAlweNy26** [comment]
The next patch is online on ThunderStore, check it out and feel free to reopen this issue if the problem persists.
