### ISSUE TITLE
Hud for inventory slots and weight

### ISSUE THREAD

**Issue by 4Magma** [zAlweNy26/AlweStats#18]
include functionality of aedenthorns  [Inventory HUD Info](https://www.nexusmods.com/valheim/mods/1089)

- used slots/max slots, and current weight/max weight
- optionally:
  - include support for backpack slots (i use [Backpack Remake](https://valheim.thunderstore.io/package/OdinPlus/BackPacks_Remake/) ) 
- could be placed in lower left corner 
- FPS could go to top left as long as you not include a RTC as former suggested

**Comment by zAlweNy26** [comment]
Ok thanks, I think I will add it in the next patch.

**Comment by zAlweNy26** [comment]
I replaced the BowStats block with the PlayerStats block and it includes inventory slots, weight, bow ammo and selected arrows. If you want, you can also modify the text of the block in the config file with the PlayerStatsFormat config setting.

Anyway, you can move every block wherever you want, just use the editing mode or manually modify the values in the config file.
