### ISSUE TITLE
Bug with container settings

### ISSUE THREAD

**Issue by IoannisK746** [zAlweNy26/AlweStats#19]
Hi,
i am using another mod wich lists all items in the container, like this
![Screenshot_878](https://user-images.githubusercontent.com/19365126/162002909-7b077bad-7748-423d-b41f-68e4e58dea95.png)

With the EnvStats enabled, even if i dont select the container tooltip, i still use this mods visual (format and colors) thats dont have any item list from the other mod. If i disable all the env stats, the other mod works fine
![Screenshot_879](https://user-images.githubusercontent.com/19365126/162003571-65c073fd-d969-4be6-996c-42c58163d242.png)

so i think its a bug on the options maybe
please check it.
thanks

**Comment by zAlweNy26** [comment]
Wait I didn't understand. You are saying that even if you disable the container in the ShowEnvStatus, you see it? Or the problem is another?

**Comment by IoannisK746** [comment]
Yes, exactly
the only way to not see it is to disable the EnvStats enable

**Comment by zAlweNy26** [comment]
Ok, I understood where the problem is. Thanks for the warning, I'll fix it in the next patch.

**Comment by IoannisK746** [comment]
Thanks

**Comment by zAlweNy26** [comment]
I should have fixed this in 4.1.0, check it out and reopen this issue if the problem persists.
