### ISSUE TITLE
Longboat speed when revesing shows zero

### ISSUE THREAD

**Issue by Gorgarn** [zAlweNy26/AlweStats#2]
see screenshots.
![2022-02-25-0734-onboat going reverse oars](https://user-images.githubusercontent.com/39360130/155717169-4c3bda05-e68f-4d18-973e-7d0cf0207cd6.png)
that said, oars when going forward are showing speed.
![2022-02-25-0736-onboat going forward oars](https://user-images.githubusercontent.com/39360130/155717241-8503160d-a0e1-42d6-ad30-d09cff420025.png)

Sorry that I did not think to check these earlier.

Some good news:
Longboat info no longer showing from shore
![2022-02-25-0738-frrom shore](https://user-images.githubusercontent.com/39360130/155717456-a7bd7a3c-571e-4b0f-a7fd-fe80f0389582.png)
and
Longboat speed shows a lower value.
![2022-02-25-0732-onboat going full forward](https://user-images.githubusercontent.com/39360130/155717726-b448a864-9b4b-4706-8a13-2400ebb42f80.png)

**Comment by zAlweNy26** [comment]
Oh yeah I forgot to show values also when revesing, I will do it as soon as I go to my pc.

**Comment by zAlweNy26** [comment]
would you rather see negative or always positive numbers even when revesing?

**Comment by zAlweNy26** [comment]
Check it out now the new version on Thunderstore 👍🏽

**Comment by Gorgarn** [comment]
Looks good, thank you!

On Fri, 25 Feb 2022 07:26:25 -0800, Dany ***@***.***> wrote:
 
 

Check it out now the new version on Thunderstore 👍🏽

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
