### ISSUE TITLE
Remark to Inventory slots

### ISSUE THREAD

**Issue by 4Magma** [zAlweNy26/AlweStats#20]
- i use randyknapp's [Equipment and Quick Slots](https://www.nexusmods.com/valheim/mods/92)
  - it shows 23/32 Slots but its only reaches 23 if i include the 8 extra slots 
  - so please increase the max by 8 or only count vanilla slots
- theres also other mods which should be covered like
  - aedenthorn's [Extended Player Inventory](https://www.nexusmods.com/valheim/mods/1356)

**Comment by zAlweNy26** [comment]
In the next patch I will include the support for other extra slots created by other mods.

**Comment by zAlweNy26** [comment]
I included the support to these two mods in the next patch, wait until I upload it. Reopen this issue if something goes wrong.
