### ISSUE TITLE
small Issue with Weight Status

### ISSUE THREAD

**Issue by 4Magma** [zAlweNy26/AlweStats#22]
- when deactivating via configuration manager, it keeps staying at this position and overlays other stat elements.
- had it deactivated because in a base are already many stat elements visible.
- btw. is it possible to color the text in the player stats box 
  - for used slots and avaiable arrows
  - as checkbox option, not extra {x}

**Comment by zAlweNy26** [comment]
If you deactivated it while inside a world, have you tried exiting and rejoining the world? If the weight status is still visible, let me know.

You can already color the text of the PlayerStats block and change the text to be displayed.

**Comment by 4Magma** [comment]
no, its gone 

had a crash (not mod related), so i can't say for world reload
