### ISSUE TITLE
Direction arrows badly visible against snow

### ISSUE THREAD

**Issue by 4Magma** [zAlweNy26/AlweStats#23]
- I'm currently at the mountain biome and the direction arrows are sometimes not to diferentiate from snowy ground
- could you 
  - make them more colorful
  - or add a dark/black outline
  - or give them a background like for your boxes
- should apply to all of your status icons which transport dynamic infos, if they aren't as colorful as the vanilla ones (direction arrows, weight bag)

**Comment by zAlweNy26** [comment]
I added a black outline to the direction arrows and weight icon in the status effects list. You will see the differences in the next patch.
