### ISSUE TITLE
[Error] NullreferenceException while lumber birches

### ISSUE THREAD

**Issue by 4Magma** [zAlweNy26/AlweStats#24]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Plant.TimeSincePlanted () (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
AlweStats.EnvStats.PatchPlantHoverText (System.String& __result, Plant __instance) (at <f4ea80b8aa1c4aa8a51b5dd243fc7ff3>:0)
(wrapper dynamic-method) Plant.DMD<Plant::GetHoverText>(Plant)
AlweStats.EnvStats.OnDamage (Destructible __instance, HitData hit) (at <f4ea80b8aa1c4aa8a51b5dd243fc7ff3>:0)
(wrapper dynamic-method) Destructible.DMD<Destructible::RPC_Damage>(Destructible,long,HitData)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Delegate.DynamicInvokeImpl (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Delegate.DynamicInvoke (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
RoutedMethod`1[T].Invoke (System.Int64 rpc, ZPackage pkg) (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
ZNetView.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData rpcData) (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
ZRoutedRpc.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData data) (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
ZRoutedRpc.InvokeRoutedRPC (System.Int64 targetPeerID, ZDOID targetZDO, System.String methodName, System.Object[] parameters) (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
ZNetView.InvokeRPC (System.String method, System.Object[] parameters) (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
(wrapper dynamic-method) Destructible.DMD<Destructible::Damage>(Destructible,HitData)
Plant.Destroy () (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
(wrapper dynamic-method) Plant.DMD<Plant::Grow>(Plant)
Plant.SUpdate () (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
SlowUpdater+<UpdateLoop>d__1.MoveNext () (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <7ed9544a6e86489c87771c638baaad47>:0)

- appeared at unknown time in log while harvesting my birch farm, so i have no further infos 
- only one error while dozens of birches, so perhaps something other in surrounding

**Comment by zAlweNy26** [comment]
I should have fixed this in the next patch. Wait until I upload it.
