### ISSUE TITLE
Compatibility with custom pins from other mods

### ISSUE THREAD

**Issue by thecybermind** [zAlweNy26/AlweStats#26]
EpicLoot mod has "bounties" and "buried treasures" that appear on the map with custom pins.

AlweStats versions after 3.8.1 (starting at 4.0.0) do not show these pins anymore.

From [EpicLoot code](https://github.com/RandyKnapp/ValheimMods/blob/3f5d6dca889b48111a663d86734e2a405543bcd3/EpicLoot/EpicLoot.cs#L153), they appear to be IDs 800 and 801:

`        public const Minimap.PinType BountyPinType = (Minimap.PinType) 800;`
`        public const Minimap.PinType TreasureMapPinType = (Minimap.PinType) 801;`

I added 800 and 801 to the AlweStats ShowCustomPins setting (and tried setting to 0) and they still do not appear.

**Comment by zAlweNy26** [comment]
The addition you made in the ShowCustomPins config setting will not affect in any way the change you want. I will try to find a way to make my mod compatible with other mods that also add custom pins.

**Comment by thecybermind** [comment]
I figured it wouldn't work, but since they were also ints I gave it a shot. I wanted to check all the settings I could find before reporting.

**Comment by zAlweNy26** [comment]
I think I fixed it. Wait until I upload the next patch, then please let me know if everything is ok !

**Comment by thecybermind** [comment]
The pins appear now (with 4.2.1), along with the text. The pin symbol is replaced with the simple round dot (they are a skull and an "X" normally), but that's a bug I can tolerate for now since the symbol isn't as important.

**Comment by zAlweNy26** [comment]
Mmmh weird, I will check about that as soon as I can. Which are the pin icons that they should be?

**Comment by thecybermind** [comment]
As far as I know, they are custom to the mod.

**Comment by zAlweNy26** [comment]
Check out the 4.2.2 patch, it should be working fine now.
