### ISSUE TITLE
Dictionary key already been added

### ISSUE THREAD

**Issue by 4Magma** [zAlweNy26/AlweStats#27]
[Error  : Unity Log] ArgumentException: An item with the same key has already been added. Key: mountaincave02(clone)
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
AlweStats.MapStats.ShowDungeonsPins (Location __instance) (at <58e89652108b40a5a71fd0e81f8f1bac>:0)
(wrapper dynamic-method) Location.DMD<Location::Awake>(Location)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
ZoneSystem:SpawnLocation(ZoneLocation, Int32, Vector3, Quaternion, SpawnMode, List`1)
ZoneSystem:SpawnProxyLocation(Int32, Int32, Vector3, Quaternion)
LocationProxy:SpawnLocation()
LocationProxy:Awake()
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
ZNetScene:CreateObject(ZDO)
ZNetScene:CreateObjectsSorted(List`1, Int32, Int32&)
ZNetScene:CreateObjects(List`1, List`1)
ZNetScene:DMD<ZNetScene::CreateDestroyObjects>(ZNetScene)
ZNetScene:DMD<ZNetScene::Update>(ZNetScene)

**Comment by zAlweNy26** [comment]
Fixed in the next patch.
