### ISSUE TITLE
[Suggestion] Hide Nearby Ship Arrow Status when on boat

### ISSUE THREAD

**Issue by codewithbjim** [zAlweNy26/AlweStats#29]
Whenever you're sailing at fullspeed in a boat the text keeps on changing from 6.8ish to 7 m and its kinda annoying to see. But great feature though.
Here's a GIF of what it looks like but the GIF just doesn't justify the speed of how the text changes from 6.8m to 7.1m or so.

![2022-04-27_23-21-48](https://user-images.githubusercontent.com/19782129/165553437-da167208-e94d-45ad-aa45-f871feab8b9f.gif)

**Comment by zAlweNy26** [comment]
Yeah, I think you are right, I never thought about that.
