### ISSUE TITLE
Incompatible with TargetPortal mod by Smoothbrain

### ISSUE THREAD

**Issue by codewithbjim** [zAlweNy26/AlweStats#31]
This mod blocks other pins added by some mods. Throws an error in the console with Invalid Pin Type

**Comment by zAlweNy26** [comment]
Can you post the error please?

**Comment by codewithbjim** [comment]
It was just a warning, I'll post the lines here once I'm on my pc. And instead of using the pins added by TargetPortal it falls back to the normal circle pin.

**Comment by zAlweNy26** [comment]
With the new patch I'll upload, the workaround will be to disable AlweStats' portal pins in the "ShowCustomPins" config setting.

**Comment by codewithbjim** [comment]
Looking forward to that. Thanks!
