### ISSUE TITLE
Compatibility with KG's Marketplace mod custom pins

### ISSUE THREAD

**Issue by xLenso** [zAlweNy26/AlweStats#33]
Hi Alweny, I noticed that you made new update to be compatible with TargetPortal's custom pins issue, would you mind to look into KG's Marketplace mod also for similar custom pins issue?

https://valheim.thunderstore.io/package/KGvalheim/Marketplace_And_Server_NPCs_Revamped/

**Comment by zAlweNy26** [comment]
Yeah I think I can do that, I will do it as soon as possible!

**Comment by zAlweNy26** [comment]
I was testing my mod to work with the one you suggested, but when I load the mod the game shows me this error : 
![image](https://user-images.githubusercontent.com/41266342/179348292-17a8abad-dbb0-45b6-a766-879452a0d880.png)
It's a problem of mine or has it happened to you too?
I understand what the error says and I think that the mod owner should be warned about that.

**Comment by xLenso** [comment]
![image](https://user-images.githubusercontent.com/96395611/179352662-f7bd585a-0172-4b6d-8076-8a4a9b9d66d9.png)

Hmm, this is the previous ss that i have, im not sure if they are the same, i will try to get a new error printed ss when i got time to log in

**Comment by zAlweNy26** [comment]
This error is not referenced to my mod, I don't know where it comes from.
