### ISSUE TITLE
Mini-map pins vanish on rotation

### ISSUE THREAD

**Issue by Seffnerca** [zAlweNy26/AlweStats#34]
Hey! Having a tiny bit of a problem with the mini-map rotation. When the map is up in the "standard way", all of the pins and character arrow show up without issue...

![image](https://user-images.githubusercontent.com/94877186/182727760-b8e68246-49b5-404e-ae92-2b90c5dc6106.png)

But when it's rotated outside of its "regular" position, everything on it vanishes. 

![image](https://user-images.githubusercontent.com/94877186/182727800-4848b80f-085b-4020-bd45-4594340c2065.png)

Chances are, this is probably my fault entirely, but I can't figure out what happened. I just started using this mod last night, and I hope someone can help. Thank you!

**Comment by zAlweNy26** [comment]
Very strange, I tested the change before publishing it, I’ll see what I can do!

**Comment by zAlweNy26** [comment]
Ok I inadvertently comment some lines of code about the rotation of the minimap ahahah

It will be fixed in the next patch!
