### ISSUE TITLE
Odin Ship support

### ISSUE THREAD

**Issue by 4Magma** [zAlweNy26/AlweStats#35]
Could you add arrow support for Odin Ship mod?

According to VEIN 

modname
- OdinShip

itemid's
- CargoShip
- BigCargoShip
- WarShip
- TransporterShip
- LittleBoat
- FishingBoat

low priority

**Comment by zAlweNy26** [comment]
I'll check what I can do!

**Comment by zAlweNy26** [comment]
I added the support to these ships but I don't know their maximum speed so the ship speed would be equal for all of them.
Do you know if they are just other versions of the game defaults or new types of ships with their own speed and health?

**Comment by zAlweNy26** [comment]
And what do you mean with "arrow support" ?

**Comment by 4Magma** [comment]
I couldn't play some months. Hasn't AlweStats also direction arrow to ship and cart or did i remember wrong?

**Comment by zAlweNy26** [comment]
Yes that's right, I thought you was talking about the ShipStats block that wasn't appearing and the map pins too, I forgot about the direction arrow ahahah
