### ISSUE TITLE
Add cooking time left on items over the fireplace

### ISSUE THREAD

**Issue by PaloAlo** [zAlweNy26/AlweStats#36]
Hi,
in section env-stats the #8 option for fireplace seems fairly unimportant since there are so many mods that affect fireplace and torch fuel. modded wards will enable permanent burning. timed torches. autofuel. etc
as you can see there are so many mods that affect fuel sources that showing stats on fireplace seems redundant.
--> a much more useful and important status effect would be the cooking time left on items over the fireplace. perhaps you might think to change this.

**Comment by zAlweNy26** [comment]
Thanks for the suggestion, I'll do what I can!

**Comment by PaloAlo** [comment]
hint: https://github.com/thedefside/BetterUI/blob/main/BetterUI/GameClasses/CookingStation.cs

**Comment by zAlweNy26** [comment]
This will be added in the next patch, wait until I finish the release and publish it.
