### ISSUE TITLE
Minimal Status Effects still incompatible

### ISSUE THREAD

**Issue by PaloAlo** [zAlweNy26/AlweStats#38]
hi, i tested the compatability with "minimal status effects" and it is broken still. 
i have a clean install with new config file, new character, single player, and just the mods needed to run the test;
bepinex
jotunn
alwestats
serverdevcommands
minimal status effects
official config manager

![image](https://user-images.githubusercontent.com/107334373/185690614-5ad0a9ac-4f77-4d91-bc04-3e99aa2f0085.png)

output shows the hud not loading properly. 

i have almost all options turned off except for weight status, entity stats, and enviro stats.

the weight icon is nowhere to be seen, but other info in middle of screen is stuck there. 

tested in two different worlds, both single player, with a different group of mods. same result.

**Comment by zAlweNy26** [comment]
I'll check that again, I obviously tested it before publishing the update and it was working fine

**Comment by zAlweNy26** [comment]
What version of the game are you running?
I tested the game version 0.209.10 and only with the mods you said and it still works fine.
There is something you missed to say?

**Comment by PaloAlo** [comment]
tested on version 209.10 both single player and dedicated server and the results were;

i didnt look at the code, but i can see that you have "linked" the status icons together. i can affirm that the mod works with everything turned on. also, if you turn off most options it will still work, but...if you turn off BED, SHIPS, PORTAL, WEIGHT status then it is incompatible with "minimal status effects" mod and it breaks the game badly.

all four of those status icons must be enabled true for the mod to work with "minimal status effects" installed.

as you state in the readme, having those status icons enabled "could cause a lowering of fps if the computer running the game is not very powerful."  For that reason i would prefer to have them disabled.  I already disable the pins, but didnt really want these other options on.

suggestion: i would move those four status icons, (and any others that are linked as they are) and move them to their own config section. then try to figure out why it will not work if even one of them is toggled off/false.

**Comment by zAlweNy26** [comment]
Thanks for the explanation, I forgot about "playing" with toggle of those status effects I created, anyway I'll try to fix this as soon as possible.

**Comment by PaloAlo** [comment]
this is a picture from my server. you can see that with "minimal status effects" installed the icons go to the right, but only if i have bed, portal, weight, and ship all enabled. also you can see that ship status doesnt actually have a name

![image](https://user-images.githubusercontent.com/107334373/186772248-6eb2bd34-1465-4533-a03c-a4e581210ac9.png)

**Comment by zAlweNy26** [comment]
Interesting, I have to check it better.

**Comment by zAlweNy26** [comment]
What ship is this? I need to check why the mod doesn't take its name.
However I solved the main problem, I had forgotten to check whether the status effects were enabled or not.

**Comment by PaloAlo** [comment]
thats the standard vanilla longship. i dont have any boat mods loaded.

**Comment by zAlweNy26** [comment]
I hope it will automatically get fixed together with the other problem since it works for me now. Let me know if something broke when I will upload the next patch!

**Comment by PaloAlo** [comment]
ofc, i will be sure to test and let you know how its going.

**Comment by PaloAlo** [comment]
seems to be working great now both server and single player

**Comment by zAlweNy26** [comment]
Thanks!
