### ISSUE TITLE
Player Info not part of PlayerStats

### ISSUE THREAD

**Issue by PaloAlo** [zAlweNy26/AlweStats#39]
hi, 

i like the added information on the character loading screen, but i feel it should be toggled on/off in its own capacity. i do not think it should be part of playerstats block. 

if i choose to turn off playerstats block then i lose all the information from the character loading screen as well.

**Comment by zAlweNy26** [comment]
Ok I will do that in the next patch

**Comment by PaloAlo** [comment]
working great!

**Comment by zAlweNy26** [comment]
Perfect!
