### ISSUE TITLE
Beehive % when full and ship stats when demolished

### ISSUE THREAD

**Issue by sfjuocekr** [zAlweNy26/AlweStats#4]
Since two or three updates ago the ship stats are not shown at all.

**Comment by zAlweNy26** [comment]
Thanks for the warning, I'll check !

**Comment by zAlweNy26** [comment]
I fixed the issue and added some new things, check it out on ThunderStore !

**Comment by sfjuocekr** [comment]
It indeed works again.

I have found a possible issue with beehive display as well, when there are four inside the hive it will tell you its progress is at 35%. But I still have to confirm it happening!

**Comment by sfjuocekr** [comment]
I think that might just be the default progress on the hive?

Anyway, the ship stats do work now. But sometimes they stay on screen after demolishing the ship with an axe.

**Comment by zAlweNy26** [comment]
> It indeed works again.
> 
> I have found a possible issue with beehive display as well, when there are four inside the hive it will tell you its progress is at 35%. But I still have to confirm it happening!

Ok I think I understood where the problem is there, when I have time I'll check and resolve this !

**Comment by zAlweNy26** [comment]
> I think that might just be the default progress on the hive?
> 
> Anyway, the ship stats do work now. But sometimes they stay on screen after demolishing the ship with an axe.

Ok I never thought about this problem, I will try to find a way to resolve this issue as soon as I can.

**Comment by zAlweNy26** [comment]
Check the new version on Thunderstore, I think I resolved these two issues !
