### ISSUE TITLE
NullreferenceException in Smelter

### ISSUE THREAD

**Issue by 4Magma** [zAlweNy26/AlweStats#42]
**Describe the bug**
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
AlweStats.EnvStats.PatchSmelterHoverText (Smelter __instance) (at <f3b9ff4fb3234e449d1e58b02b9dce43>:0)
(wrapper dynamic-method) Smelter.DMD<Smelter::UpdateHoverTexts>(Smelter)
Smelter.FixedUpdate () (at <94f274a921864d9db4f1d2703c897047>:0)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by zAlweNy26** [comment]
Can you give me some hints on how it came out? You were smelting something or just placing some coal in it?

**Comment by 4Magma** [comment]
- Have currently no smelter or killn built
- get rid of it by removing 11 from Config > ShowEnvStatus
- first noticed while visit in base, but only because of alt tab to an other program

**Comment by zAlweNy26** [comment]
Ok thanks, I'll try to fix that as soon as possible

**Comment by zAlweNy26** [comment]
I should have fixed this, feel free to reopen this issue if you encounter this error again with the next patch.
