### ISSUE TITLE
Smelter error

### ISSUE THREAD

**Issue by PaloAlo** [zAlweNy26/AlweStats#43]
![image](https://user-images.githubusercontent.com/107334373/185808988-5204745a-c873-4835-aced-8082446244c6.png)

**Describe the bug**
getting this repeating error in my output. 

**To Reproduce**
tbh im having a hard time reproduing this. it only happens at one players base, not anywhere else that i could tell on the server. 

UPDATE: im going to say lets just archive this for later, in case anyone else ever has an issue like this. it seems to be a problem with one base, not the player, but that location, and i cannot reproduce it anywhere else. 

**Expected behavior**
i turned off option 11 "smelter status" in the environment stats section and relogged, and the problem was gone. so, not sure why its doing this at this players base. i even asked him to break and remake both the smelter and blast furnace but the error persisted.

**Screenshots**
attached

**Comment by zAlweNy26** [comment]
Yeah another guy created an issue about a smelter error in the logs, I should have fixed this in the next patch. Let me know if you encounter this error again after I publish the update.

**Comment by Squeech007** [comment]
Hi, i jut got this error as well. today. i think its related to the second tier (black metal) smelter. because i just didnt get it before i build it.

**Comment by zAlweNy26** [comment]
Thanks for the warning, I'll fix it when I have time.

**Comment by PaloAlo** [comment]
bug is back after the latest game update from Iron Gate. users have reported that it only happens around the blast furnace. i cant confirm if that is accurate or not.

**Comment by PaloAlo** [comment]
i got this today, same smelter issue as before, but there was another error immediately after that may or may not be related.  if it is part of the problem it might give some insight.


[Error  : Unity Log] FormatException: Input string was not in a correct format.
Stack trace:
System.Number.StringToNumber (System.String str, System.Globalization.NumberStyles options, System.Number+NumberBuffer& number, System.Globalization.NumberFormatInfo info, System.Boolean parseDecimal) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Number.ParseInt32 (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Int32.Parse (System.String s, System.IFormatProvider provider) (at <695d1cc93cca45069c528c15c9fdd749>:0)
AlweStats.Utilities+<>c__6`1[T].<CheckInEnum>b__6_0 (System.String s) (at <d6aecd84ec3c47b19503f4428517c20a>:0)
System.Array.ConvertAll[TInput,TOutput] (TInput[] array, System.Converter`2[TInput,TOutput] converter) (at <695d1cc93cca45069c528c15c9fdd749>:0)
AlweStats.Utilities.CheckInEnum[T] (T type, System.String setting) (at <d6aecd84ec3c47b19503f4428517c20a>:0)
AlweStats.EnvStats.PatchSmelterHoverText (Smelter __instance) (at <d6aecd84ec3c47b19503f4428517c20a>:0)
(wrapper dynamic-method) Smelter.DMD<Smelter::UpdateHoverTexts>(Smelter)
Smelter.FixedUpdate () (at <cdb5bbec33f94182b860ca208c683122>:0)

[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "itemstandh(Clone)/attach_other/attach(Clone)/Helm/Cube (2)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "itemstandh(Clone)/attach_other/attach(Clone)/Helm/Cube (1)"

**Comment by PaloAlo** [comment]
You are using
CountItems(string)
when it is now
CountItems(string,int)
same happens with renames
anything that changes the method signature causes that error

**Comment by zAlweNy26** [comment]
I'm not using a CountItems function, what are you talking about, @PaloAlo ?

**Comment by LabManCam** [comment]
I just installed this mod recently and am getting this error as well now. 

`NullReferenceException: Object reference not set to an instance of an object
  at AlweStats.EnvStats.PatchSmelterHoverText (Smelter __instance) [0x000c0] in <a758abd4edcf454b976fb9a286a560ea>:0 
  at (wrapper dynamic-method) Smelter.DMD<Smelter::UpdateHoverTexts>(Smelter)
  at Smelter.FixedUpdate () [0x0000e] in <35c0f7aa1999477788815a7bf78200d7>:0 

NullReferenceException: Object reference not set to an instance of an object
  at AlweStats.EnvStats.PatchSmelterHoverText (Smelter __instance) [0x000c0] in <a758abd4edcf454b976fb9a286a560ea>:0 
  at (wrapper dynamic-method) Smelter.DMD<Smelter::UpdateHoverTexts>(Smelter)
  at Smelter.FixedUpdate () [0x0000e] in <35c0f7aa1999477788815a7bf78200d7>:0 

NullReferenceException: Object reference not set to an instance of an object
  at AlweStats.EnvStats.PatchSmelterHoverText (Smelter __instance) [0x000c0] in <a758abd4edcf454b976fb9a286a560ea>:0 
  at (wrapper dynamic-method) Smelter.DMD<Smelter::UpdateHoverTexts>(Smelter)
  at Smelter.FixedUpdate () [0x0000e] in <35c0f7aa1999477788815a7bf78200d7>:0 

NullReferenceException: Object reference not set to an instance of an object
  at AlweStats.EnvStats.PatchSmelterHoverText (Smelter __instance) [0x000c0] in <a758abd4edcf454b976fb9a286a560ea>:0 
  at (wrapper dynamic-method) Smelter.DMD<Smelter::UpdateHoverTexts>(Smelter)
  at Smelter.FixedUpdate () [0x0000e] in <35c0f7aa1999477788815a7bf78200d7>:0 `
  
It is triggering every frame that I have a smelter loaded in the area. I was debating just pulling down a copy and removing the smelter from the utilities.cs enum, but was unsure if that would cause other issues.

If you need more details, let me know, but it is looking like the exact same issues as experienced above.

**Comment by zAlweNy26** [comment]
I found the issue and fixed it, please wait for the next patch.
