### ISSUE TITLE
HarmonyX warning on quit

### ISSUE THREAD

**Issue by PaloAlo** [zAlweNy26/AlweStats#45]
hi, getting the following on logout. i disable the mod and then no msg on quit, so it is definitely this mod. i dont have minimal status effects installed so no conflict there.

[Info   : Unity Log] 08/27/2022 12:26:57: Game - OnApplicationQuit

[Warning:  HarmonyX] AccessTools.GetTypesFromAssembly: assembly System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 => System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at HarmonyLib.AccessTools.GetTypesFromAssembly (System.Reflection.Assembly assembly) [0x0000d] in <474744d65d8e460fa08cd5fd82b5d65f>:0 
[Warning:  HarmonyX] AccessTools.GetTypesFromAssembly: assembly System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 => System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at HarmonyLib.AccessTools.GetTypesFromAssembly (System.Reflection.Assembly assembly) [0x0000d] in <474744d65d8e460fa08cd5fd82b5d65f>:0 
[Info   : Unity Log] The config file of AlweStats was reloaded successfully !
[LogOutput.log](https://github.com/zAlweNy26/AlweStats/files/9438557/LogOutput.log)

**Comment by zAlweNy26** [comment]
Let me know if it persists in the next patch.

**Comment by PaloAlo** [comment]
still there

**Comment by zAlweNy26** [comment]
Mh okay, I will debug until I find what causes this warning.

**Comment by PaloAlo** [comment]
why is it doing a reload of the config when its supposed to be shutting down? in my limited knowledge most mods as i understand it will call an  "unpatch:self"  (if needed) on shutdown.

**Comment by PaloAlo** [comment]
wait,,, its a mod conflict. disabling your mod makes the warning go away, but in a smaller test profile with only about 10 mods  (not my 75 slot modpack) it did not produce the warning. so im testing now to see if i can find which mod is causing a conflict on shutdown with your mod.

**Comment by zAlweNy26** [comment]
I do the UnpatchSelf() on shutdown. Tell me if you find which mod create the conflict so I can fix that.

**Comment by PaloAlo** [comment]
i tested with just alwestats, bepinex, and Rune Magic by hyleanlegend.  seems to cause the error from your mod. 
i tested with my entire modpack, disabled rune magic and no problems. however with rune magic enabled it throws the error on shutdown.
i have to assume it is that mod and only that one because with just two mods or 75 it throws the error if that mod is enabled

**Comment by zAlweNy26** [comment]
Thanks for the testing, I'll check what I can do to resolve the conflict with Rune Magic mod.

**Comment by zAlweNy26** [comment]
I don't find what generates this warning, anyway as it is just a warning, you can simply don't care about that.

**Comment by PaloAlo** [comment]
yes, only a warning, so no big deal. as long as its not interfering with a proper shutdown then i will ignore it.

**Comment by PaloAlo** [comment]
i have to wonder though, why is your mod trying to reload the config file on shutdown? i mean that seems like the reason you get the error 'System.Reflection.ReflectionTypeLoadException' was thrown'
throws a load error,, because you are reloading the config on shutdown
just my thoughts out loud... and i have no idea why that would be a conflict with rune magic

**Comment by zAlweNy26** [comment]
I should have fixed this in the next patch, feel free to reopen this issue if the warning persists!

**Comment by PaloAlo** [comment]
it looked like it worked, ,but then after i opened and closed a second time i got this

[Warning:  HarmonyX] AccessTools.GetTypesFromAssembly: assembly System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 => System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at HarmonyLib.AccessTools.GetTypesFromAssembly (System.Reflection.Assembly assembly) [0x0000d] in <474744d65d8e460fa08cd5fd82b5d65f>:0 
[Warning:  HarmonyX] AccessTools.GetTypesFromAssembly: assembly System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 => System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at HarmonyLib.AccessTools.GetTypesFromAssembly (System.Reflection.Assembly assembly) [0x0000d] in <474744d65d8e460fa08cd5fd82b5d65f>:0 
[Info   : Unity Log] The config file of AlweStats was saved successfully !

**Comment by zAlweNy26** [comment]
I don't know why it gives you this problem, these assembly files were integrated into the mod and gave me no problem. Could it be a problem of RuneMagic?

**Comment by PaloAlo** [comment]
dev mod for Rune Magic fixed/updated something in his mod and the error is gone now. just wanted to let you know. all is well.

**Comment by zAlweNy26** [comment]
Thanks for letting me know!
