### ISSUE TITLE
Broken map icons

### ISSUE THREAD

**Issue by Azzinoth224** [zAlweNy26/AlweStats#47]
The map icons for portals, ships and carts are replaced by white circles instead of the correct ones from the mod.

This happend when I changed the ini to display only these icons and not crypts etc. Afterwards the removed icons where replaced by orange markers, so I deleted all map icons manually (including portals, ships and carts) thinking that it would regenerate the correct ones after restarting the game with new settings. Ever since then I have the white circles.

I tried deleting the json, manually removing the icons again and restarting the game, but I have not found any way to fix it so far.

![valheim_icons](https://user-images.githubusercontent.com/34380874/197253576-7ebf5e27-ec52-42fc-ae97-ec20368623ec.jpg)

**Comment by zAlweNy26** [comment]
I found a fix for that, with the next patch the custom pins will get removed on game exit so this problem will not persists if you deactivate the pins or uninstall the mod.
Unluckily, you must first remove the white circles all by yourself.
