### ISSUE TITLE
Error if no arrows in inventory

### ISSUE THREAD

**Issue by 4Magma** [zAlweNy26/AlweStats#5]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
AlweStats.BowStats.Update () (at <34facf3403fa478c84b4bc3c152e72ac>:0)
AlweStats.Main+PluginPatches.PatchHudUpdate () (at <34facf3403fa478c84b4bc3c152e72ac>:0)
(wrapper dynamic-method) Hud.DMD<Hud::Update>(Hud)

first detected with 3.1, also found in 3.2.1

**Comment by zAlweNy26** [comment]
Thank you for the warning, I will fix this as soon as I can !

**Comment by zAlweNy26** [comment]
I resolved this in 3.2.2, check it out on Thunderstore !
