### ISSUE TITLE
HP Bars

### ISSUE THREAD

**Issue by NakulDK** [zAlweNy26/AlweStats#51]
**Is your feature request related to a problem? Please describe.**
Just started using the mod, and it's impressive how much information you have in it!
The one thing I found both good and bad is the HP bars, they seem very chunky and as far as I can see no setting to them, well except tamed, but that only effects a limited amount of mobs.

**Describe the solution you'd like**
Some settings, like changing the size and colour of the bar
Personally I really don't get the Red/Green/Red look of it, would much prefer a full red line, but perhaps it's showing something I simply don't understand :p

**Comment by zAlweNy26** [comment]
Hi, thanks for opening the issue.
I only color the health bar for tamed animals, and you can change it with the "TamedBarColor" config setting.
I will add the possibility to change size and color of the health bars.

**Comment by zAlweNy26** [comment]
I added some new config settings, please wait until the next patch.
Let me know if everything is fine if you want!

**Comment by NakulDK** [comment]
Something is going on with the HPbar I don't understand, the green bar in the middle of both untamed and tamed is always full, can you tell me what it shows?
I like the change of colour in regards to tamed/untamed, but would really just like the green bar in the middle to go away, so it's just a full red (untamed) or full blue (tamed) when looking at them :)

![tamed no mod](https://user-images.githubusercontent.com/45997053/216767630-8558aea8-60d3-4c07-b4f2-f69557214d7a.png)
![tamed with mod](https://user-images.githubusercontent.com/45997053/216767631-f085ead8-e312-4a97-a666-8d3d69c949e9.png)
![untamed damaged no mod](https://user-images.githubusercontent.com/45997053/216767632-5a02e950-1e18-4360-9ad4-4c3ea5077f35.png)
![untamed damaged with mod](https://user-images.githubusercontent.com/45997053/216767633-c5c830e2-5924-46ea-9b73-8ab8c10936c4.png)

**Comment by zAlweNy26** [comment]
I really don't know why they added this green bar in the middle of the health bar ahahah
So for now I forced it to not show until I find its meaning.
