### ISSUE TITLE
ServerStats block doesn't appear

### ISSUE THREAD

**Issue by NakulDK** [zAlweNy26/AlweStats#52]
Can't get the server stat block to show
Tried setting the position and margin the same as another block but it does not show, also tried disabling it and enabling it again, nothing :S

**Comment by NakulDK** [comment]
Just tried uninstalling and removing the config file, typing in all the changes I've med again, and the server stat block still does not pop up :(

**Comment by zAlweNy26** [comment]
I will check again to see if there is anything that doesn't work.
Are you sure you are in a server, right?
Were you alone in the server?
Is the server hosted by you?

**Comment by NakulDK** [comment]
Been playing around with it a bit more, and I've seen it pop up when I hosted a private world, with crossplay enabled and another person joined.
When this person left the server, his name was still showing as connected tho.
I've yet to see it show up when joining a dedicated server or any other persons worlds.

**Comment by zAlweNy26** [comment]
I removed the check to see if there is more than 1 player and if the ping is greater than 0. I will upload the next patch, let me know if the problem persists.

**Comment by NakulDK** [comment]
Now it works flawlessly when hosting a private world. It registers players leaving and everything.
However, still don't see anything on dedicated servers or other peoples worlds :(

**Comment by zAlweNy26** [comment]
Thanks for reporting this, unfortunately I don't play in any server so it's difficult to me to check that. I'll do the possible.

**Comment by zAlweNy26** [comment]
Fixed in the next patch! :)
