### ISSUE TITLE
WorldStats Update error

### ISSUE THREAD

**Issue by Saemer2023** [zAlweNy26/AlweStats#53]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
AlweStats.WorldStats.Update () (at <a758abd4edcf454b976fb9a286a560ea>:0)
AlweStats.Main+PluginPatches.PatchGame () (at <a758abd4edcf454b976fb9a286a560ea>:0)
(wrapper dynamic-method) ZNetScene.DMD<ZNetScene::Update>(ZNetScene)
![1675331295947](https://user-images.githubusercontent.com/124252195/216290712-ffff31bc-df50-4597-b54a-eafb2be9f57b.png)
![1675331354979](https://user-images.githubusercontent.com/124252195/216290923-f32e3551-9c8c-40ce-8f87-ed1a02582e92.png)

**Comment by zAlweNy26** [comment]
Were you in a server? It appeared on world join or after a specific action? And if yes, what?

**Comment by zAlweNy26** [comment]
I should have fixed this. Please wait until I upload the next patch.
Let me know if the problem persists by reopening this issue.
