### ISSUE TITLE
Config optimization

### ISSUE THREAD

**Issue by NakulDK** [zAlweNy26/AlweStats#55]
**Is your feature request related to a problem? Please describe.**
Nope simply ease of use

**Describe the solution you'd like**
Move the formatting of each type from generan to the individual section.

For example 
General / PlayerStatsFormat to PlayerStats / PlayerStatsFormat

**Comment by zAlweNy26** [comment]
When I'll have a bunch of fixes I'll upload this change too. Thanks for the suggestion.

**Comment by zAlweNy26** [comment]
I decided to not do this change because there are too many settings in the "General" section and I don't want to annoy some players into manually moving all the settings from one section to another. Also, this change doesn't affect the functioning of the mod, so I think it is not worth it.
