### ISSUE TITLE
Error when changing custom pins, MapStats toggle not working

### ISSUE THREAD

**Issue by greenconda** [zAlweNy26/AlweStats#56]
**Describe the bug**

Changing custom pin settings throw error, and map stats stop working completely

**To Reproduce**
1. Edit cfg file for map stats
2. Change custom pin value, I tried many but zero for example
3. start game
4. error in console and map stats dont work anymore

**Expected behavior**
Working Properly

Error Log Message:

[Error  : Unity Log] InvalidOperationException: Sequence contains no matching element
Stack trace:
System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
AlweStats.MapStats.SetElementStatus (UnityEngine.GameObject element, System.Collections.Generic.List`1[T] list, UnityEngine.Vector2 playerPos, UnityEngine.Transform camera, System.Int32 space) (at <9786940ed57e442cac39697399dc7e07>:0)
AlweStats.MapStats.MinimapUpdate (Minimap __instance) (at <9786940ed57e442cac39697399dc7e07>:0)
(wrapper dynamic-method) Minimap.DMD<Minimap::Update>(Minimap)

[Error  : Unity Log] InvalidOperationException: Sequence contains no matching element
Stack trace:
System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
AlweStats.MapStats.SetElementStatus (UnityEngine.GameObject element, System.Collections.Generic.List`1[T] list, UnityEngine.Vector2 playerPos, UnityEngine.Transform camera, System.Int32 space) (at <9786940ed57e442cac39697399dc7e07>:0)
AlweStats.MapStats.MinimapUpdate (Minimap __instance) (at <9786940ed57e442cac39697399dc7e07>:0)
(wrapper dynamic-method) Minimap.DMD<Minimap::Update>(Minimap)

**Comment by zAlweNy26** [comment]
Hi, can you show me the portion of the cfg file about the custom pins settings?

**Comment by greenconda** [comment]
Its working as expected when I tried today, even multiple times, so I am not sure where the issue was, maybe some other mod was causing issues, though I cant pinpoint it to any. But thank you.

**Comment by greenconda** [comment]
There is definitely some issue with that setting, reinstalling the mod made the problem appear again. This time also when selecting pins 4,5,6 the custom image of pins was replaced by white circle. It works as intended if the setting is kept at default value. 

This is the setting I am talking about 

## Toggle specific custom pins, separate them with a comma (,)
## 0 = disable all the custom pins
## 1 = troll caves pins
## 2 = crypts pins
## 3 = fire holes pins
## 4 = portals pins
## 5 = ships pins
## 6 = carts pins
## 7 = mountain caves pins
## 8 = runestone pins
## 9 = infested mines pins
# Setting type: String
# Default value: 1, 2, 3, 4, 5, 6, 7, 8, 9
ShowCustomPins = 4,5,6

**Comment by zAlweNy26** [comment]
Ok thanks for the warning, I'll check what I can do.

**Comment by zAlweNy26** [comment]
It should be get solved in the next patch, feel free to reopen with issue if the error persists.
