### ISSUE TITLE
Incompatible with version 0.214.2

### ISSUE THREAD

**Issue by Babkatt** [zAlweNy26/AlweStats#58]
**Describe the bug**
After update today, March 13, have issue with the world choice panel. The local world menu is blank, then when clicking on join game, the menus seem to overlap. Deduced it down to this mod by disabling everything except bepinex and this mod. And when joining game, most of the UI is broken. It's showing wrong info or displaying things when they're not pertinent. Attached two screenshots showing menu and in-game.

Specifics on the in-game screenshot, the network icon on the top left, the food/health bar is not displaying proper info (the foods eaten and current health are not depicting actual info), the entity health in bottom middle is inaccurate, wood roof, equipping sword, showing all the stacks of wood, and showing controller info in the middle of the screen (don't even play with a controller).
![20230313093233_1](https://user-images.githubusercontent.com/127775044/224768264-68d34ee8-7619-4752-85f3-b84549a9540a.jpg)
![20230313093552_1](https://user-images.githubusercontent.com/127775044/224768269-0179fe5c-4c40-48a0-bfea-3cff4ee389dd.jpg)

**Comment by zAlweNy26** [comment]
I'm sorry to hear this, but to have a better understanding I need to know what happens in the console. Do you get any errors when you are in the world selection menu? And what about when you are in game?

**Comment by Babkatt** [comment]
I got a ton of "MissingFieldException: Field" in the player.log. The console itself isn't showing anything. Not sure why as it normally shows more than just the game version number. Uploaded my player.log.
[Player.log](https://github.com/zAlweNy26/AlweStats/files/10960278/Player.log)

**Comment by zAlweNy26** [comment]
I don't know what you did to your game files, but the error:
```c#
MissingFieldException: Field 'FejdStartup.m_worldSourceInfo' not found.
  at (wrapper dynamic-method) FejdStartup.DMD<FejdStartup::UpdateWorldList>(FejdStartup,bool
```

is generated by the game itself, it is not produced by AlweStats. And also the error
```c#
NullReferenceException: Object reference not set to an instance of an object
  at FejdStartup.OnCharacterStart () [0x00099] in <afd4e3f8ab8b460f8ff25d476fbd573e>:
```

After these errors, my mod is obviously generating errors in portions of the code that were using basic game functions.
There are also a lot of other errors (always generated by the game itself) like
```c#
MissingFieldException: Field 'EnemyHud/HudData.m_staminaText' not found.
  at (wrapper dynamic-method) EnemyHud.DMD<EnemyHud::UpdateHuds>(EnemyHud,Player,Sadle,single)
  at EnemyHud.LateUpdate () [0x000c2] in <afd4e3f8ab8b460f8ff25d476fbd573e>:0
```

...and many others. I suggest a reinstallation of the game.

**Comment by Babkatt** [comment]
This all happened with a clean installation. The mod broke with todays update. Was working fine last night.

**Comment by zAlweNy26** [comment]
Ok I checked, I didn't know there was an update. I'll check what I can do as soon as possible and update the mod.

**Comment by Babkatt** [comment]
Yeah seemed odd. Update few days ago notes the same changes as today's yet broke a few mods. Texture stuff is crashing the game as well as UI stuff being messed up. ReforgedUI doesn't work either.

**Comment by zAlweNy26** [comment]
I updated the mod, feel free to reopen this issue if you find any error.
