### ISSUE TITLE
Map pins have wrong position

### ISSUE THREAD

**Issue by Babkatt** [zAlweNy26/AlweStats#59]
With this mod active, since last game update, noticed that when deleting map pins, the names become locked in their place and move around whenever you move the map. Not sure if it's a certain setting but does it in single player and multiplayer. Doesn't happen with this mod disabled.

**To Reproduce**
1. place map pin
2. delete map pin
3. no profit?

screenshot added
![20230315174822_1](https://user-images.githubusercontent.com/127775044/225481013-af83fc8f-380b-461a-a53c-6fe325901e88.jpg)

**Comment by zAlweNy26** [comment]
Did you get any error in the console?

**Comment by Babkatt** [comment]
No. Nothing in console besides it saying [Info :Unity Log] date, time: Right Click.

**Comment by BDVBurik** [comment]
![image](https://user-images.githubusercontent.com/21007812/229002380-73fa1752-3370-4870-8c19-da3f4ee3ddc6.png)
after removing the pin, the text remains until re-entering the game

**Comment by zAlweNy26** [comment]
Ok, I'll check what I can do.

**Comment by rwdj** [comment]
I have the same issue. No logs. I had everything disabled except ship stats, so it was hours of debugging my personal mod before I realized it was this mod by disabling all other mods (including my own). I didn't even know this mod affected pins. All I wanted was ship stats.

**Comment by zAlweNy26** [comment]
After which game update did you encounter this problem?
Do you have any other mods that affect pins?
Have you tried disabling my mod's pins and trying again? And the same for the other mod's pins functionalities.

**Comment by zAlweNy26** [comment]
Fixed in the next patch
