### ISSUE TITLE
BowStats error when having 0 arrows

### ISSUE THREAD

**Issue by brianmiller** [zAlweNy26/AlweStats#6]
![image](https://user-images.githubusercontent.com/342276/156937990-73bed8eb-9000-4d6a-921f-bcbc734d9bec.png)

**Comment by brianmiller** [comment]
My bad... it looks like this was open 2hrs ago. :)

https://github.com/zAlweNy26/AlweStats/issues/5

**Comment by zAlweNy26** [comment]
No problem, thanks you too for the warning, I resolved this in 3.2.2, check it out on Thunderstore !

**Comment by brianmiller** [comment]
The arrow errors are gone. But I see this when attempting to edit the HUD.

![image](https://user-images.githubusercontent.com/342276/156942383-fcde0237-5660-4783-98c1-74bf3b0f8b0a.png)
