### ISSUE TITLE
Minimap rotating error / Localization problem

### ISSUE THREAD

**Issue by BDVBurik** [zAlweNy26/AlweStats#60]
![image](https://user-images.githubusercontent.com/21007812/229001711-6184cedb-32c1-4eb6-b52b-35641afa815e.png)
![image](https://user-images.githubusercontent.com/21007812/229001787-d6473151-eb0f-4801-a594-39c0b9280593.png) 
the minimap has stopped rotating, the arrow is running sideways or backwards

**Comment by zAlweNy26** [comment]
Hi, have you removed some entries from the AlweStats.translations.json ? If yes, restore the original file and restart the game. If the problem persists, let me know.

**Comment by BDVBurik** [comment]
no, I didn't delete anything.. I reinstalled the mod.. everything is the same
![image](https://user-images.githubusercontent.com/21007812/229371732-8b4b9a8d-893f-4c43-b0f5-8b8f79a7d6ad.png)
![image](https://user-images.githubusercontent.com/21007812/229371756-72297fc3-1433-41d6-b8f0-9662fa25d56e.png)

**Comment by zAlweNy26** [comment]
It seems that the game doesn't find the localization word, I'll check which is the problem.

**Comment by BDVBurik** [comment]
Ukrainian localization

**Comment by zAlweNy26** [comment]
> Ukrainian localization

Can I see your AlweStats.translations.json ?

**Comment by zAlweNy26** [comment]
I hope it will get fixed in the next patch, reopen this issue if the problem persists.
