### ISSUE TITLE
Map pin titles not removing when pin is

### ISSUE THREAD

**Issue by KyriadosX** [zAlweNy26/AlweStats#62]
**Describe the bug**
Title. Whenever a map pin is created with a title, and the pin is deleted, the title stays behind. Worse even, the title is then static to the position of the screen, rather than the map itself, so the title remains "burned" even if you pan or zoom away from the location the pin was in.

**To Reproduce**
1. Created a pin of any type on the map (or proceed directly to Step 2 if not deleting a manually created pin).
2. Right-click a pin with a title (manually created or auto-generated through whatever means, doesn't seem to matter).
3. Title stays behind, static to the screen. Only appears when the map is open.

**Expected behavior**
Map pin titles should be deleted when pins are.

**Screenshots**
![image](https://user-images.githubusercontent.com/51899759/233569307-1c7c02b1-cb32-4d3a-8794-db6450d89b96.png)
![image](https://user-images.githubusercontent.com/51899759/233569463-e200c06a-0e06-4ba1-a5ef-d5cd96117bc1.png)
![image](https://user-images.githubusercontent.com/51899759/233569732-8cd26b6e-c425-4ddc-8d00-561efc33f16b.png)
![image](https://user-images.githubusercontent.com/51899759/233569988-a8f67a5e-7e81-4dba-8ad1-cd80ee035caa.png)

**Comment by KyriadosX** [comment]
Additional information:
This occurs even when every option in the mod is set to "False", with the mod still active. The mod being inactive removes the issue.

**Comment by zAlweNy26** [comment]
Fixed in the next patch
