### ISSUE TITLE
ShipStats behaves erratically for any ship past the first one you get in per session

### ISSUE THREAD

**Issue by Cathode88** [zAlweNy26/AlweStats#63]
**Describe the bug**
ShipStats behaves erratically for any ship past the first one you get in per session. It works perfectly for the first ship, but if you hop in to another ship the frame/text disappears intermittently. Sometimes being gone for minutes only to show up for a second and then being gone again. Going back to the first ship it works perfectly again. Logout, and then loading back in to the world can be used as a workaround.

Sometimes touching terrain or colliding with other ships seems to sometime make it show up, but often disappears again a few seconds. 
Other times, no matter what I do, I can't make it show up for any but the first ship I get in to.
At one point during my testing I tried sticking with it instead, maneuvering around to try to make it reappear time and time again, and suddenly it just started working for all ships. After logout -> load in, the issue was back however.

Tested with r2modman, only bepinex and AlweStats.

**To Reproduce**
1. Load in to a world.
2. Build two Rafts.
3. Only the first built will have ShipStats working.
4. Stand on the non-working Raft, logout and back in again. Now the one you logged out on works and the other one doesn't.

**Expected behavior**
For ShipStats to show up on any and all ships. 
**Screenshots**

**Comment by zAlweNy26** [comment]
I know this issue, unfortunately I still haven't found a better way to make it works.

**Comment by Cathode88** [comment]
It seems like Ship_Stats by Azumatt has the EXACT same issue. So I guess we can chalk this up to an engine limitation/bug.

**Comment by zAlweNy26** [comment]
It's an issue related to how the events work on the vanilla Valheim, we can just wait for them to make it better or implement the logic by ourselves. I'll close the issue.
