### ISSUE TITLE
Cooking station/stone oven text 

### ISSUE THREAD

**Issue by Cathode88** [zAlweNy26/AlweStats#64]
**Describe the bug**
Cooking station shows "<color=lime>69%" instead of actually coloring the text. I have seen reports of the same issue with other mods. Seems like a recent Valheim patch made "lime" not a valid color any more.

https://github.com/zAlweNy26/AlweStats/blob/f98f9d6c46ff56ff6500dd502e8f68631da0bbf5/EnvStats.cs#LL231C2-L231C2

**To Reproduce**
1. Grill something on a cooking station
2. See error

**Expected behavior**
Green text.

**Screenshots**
![AlweStatsCookingstation](https://github.com/zAlweNy26/AlweStats/assets/101648823/576557de-801c-41ab-b478-993d23e8b952)

**Comment by zAlweNy26** [comment]
So I think I have to turn the lime into green.

**Comment by Cathode88** [comment]
Just noticed that the Stone Oven has the same issue.
Fuel/burn time seems to be missing for it too.

**Comment by zAlweNy26** [comment]
Without errors?
Can you post a screenshot?

**Comment by Cathode88** [comment]
Fuel timer missing
![image](https://github.com/zAlweNy26/AlweStats/assets/101648823/8728594a-855f-4000-ba86-551a04dbe7c0)
Cooking color
![image](https://github.com/zAlweNy26/AlweStats/assets/101648823/83ff527e-72d8-4d9a-8ae0-32a6c86aa933)

The oven is a bit odd having 3 different surfaces that displays different info when hovered.
![image](https://github.com/zAlweNy26/AlweStats/assets/101648823/ffe73975-c26f-4a30-858b-9f28706a7a3c)

Red area is NOT interactable, but still shows while cooking:
![image](https://github.com/zAlweNy26/AlweStats/assets/101648823/f02fe289-a0dc-4d46-8deb-8e9a9966b7c4)
**It shows no text when the oven is empty (not actively cooking)**

Green area is interactable and shows:
![image](https://github.com/zAlweNy26/AlweStats/assets/101648823/dfd7e9df-748e-4506-b78d-c2f7cf246d1c)

Blue area is interactable and shows:
![image](https://github.com/zAlweNy26/AlweStats/assets/101648823/59d37045-435d-44da-bdd9-e0577eba494f)

**Comment by zAlweNy26** [comment]
This should be fixed, please update the mod
