### ISSUE TITLE
Valheim 0.216.9 broke the mod

### ISSUE THREAD

**Issue by Cathode88** [zAlweNy26/AlweStats#65]
Monday's patch 0.216.9 completely broke the mod. Error messages as follows.

**Starting up the game with mod loaded:** 
> [Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type Smelter and name UpdateHoverTexts and parameters
> [Error  : Unity Log] ArgumentException: Undefined target method for patch method static void AlweStats.EnvStats::PatchSmelterHoverText(Smelter __instance)
> Stack trace:
> HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> Rethrow as HarmonyException: Patching exception in method null
> HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> HarmonyLib.Harmony.PatchAll () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> AlweStats.Main.Start () (at <46d92ae7cf9f4e98aafe83d32ea4eb3c>:0)

**While in a world:** 
> [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
> Stack trace:
> AlweStats.EntityStats.ShowHud (EnemyHud& __instance, Character c, System.Boolean isMount) (at <46d92ae7cf9f4e98aafe83d32ea4eb3c>:0)
> (wrapper dynamic-method) EnemyHud.DMD<EnemyHud::ShowHud>(EnemyHud,Character,bool)
> EnemyHud.LateUpdate () (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)

While in a game, and as soon as you get in range with a enemy, the console gets absolutely spammed with the error message and FPS drops to about 2. The health bar elements are stuck to the screen like this:
![image](https://github.com/zAlweNy26/AlweStats/assets/101648823/6d13285a-36f8-49a2-82b3-8b2db611794f)

**Comment by zAlweNy26** [comment]
Thank you for the warning, I'll fix as soon as I can

**Comment by zAlweNy26** [comment]
This should be fixed, please update the mod
