### ISSUE TITLE
AlweStats is broken for the new update

### ISSUE THREAD

**Issue by sfjuocekr** [zAlweNy26/AlweStats#66]
The game got updated and this addon causes the text "Some text" to appear together with the development console.

You can not close the development console and the addon seems to be non-working upon loading a world.

**Comment by zAlweNy26** [comment]
Hi, can you please attach a screenshot of the error that appears in the console?

**Comment by sfjuocekr** [comment]
**
![image](https://github.com/zAlweNy26/AlweStats/assets/398018/a47b7f5a-c3ad-4e2b-9329-c627db94bc7f)
**

This is what it shows.

**Comment by sfjuocekr** [comment]
[Player.log](https://github.com/zAlweNy26/AlweStats/files/12441767/Player.log)

This is the player.log
