### ISSUE TITLE
Error when editing mode is enabled

### ISSUE THREAD

**Issue by brianmiller** [zAlweNy26/AlweStats#7]
![image](https://user-images.githubusercontent.com/342276/156942456-73746039-2e0a-4faf-882a-89e8f3714218.png)

**Comment by zAlweNy26** [comment]
More precisely, when it occurs?

**Comment by brianmiller** [comment]
I believe it appeared when I attempted to move the Bow HUD element.

**Comment by zAlweNy26** [comment]
So for the others blocks it works fine and it doesn't generate this error?

**Comment by brianmiller** [comment]
checking..

**Comment by brianmiller** [comment]
* I connect to my world (multi-player/dedicated dockerized server)
* Open console (F5)
* Press F9 for Alwestats HUD editing mode

This scrolls.  I'm not able move any elements either. I was wrong, it's not just the BowStats element.  It's whenever editing mode is enabled.

The scrolling of errors in the console instantly stops when HUD editing mode is disabled.

![image](https://user-images.githubusercontent.com/342276/156943424-6b8f114e-aa5d-4b41-8d1e-cc5654e1e4fd.png)

**Comment by zAlweNy26** [comment]
Ok thanks for the warning, I'll check about this as soon as I can

**Comment by zAlweNy26** [comment]
I don't know why this error doesn't occur on my game instance, have you tried different ways to make this work?

**Comment by zAlweNy26** [comment]
Check it out the new version on Thunderstore and let me know if you find this error again

**Comment by brianmiller** [comment]
Same issue. :(

![image](https://user-images.githubusercontent.com/342276/157508627-c86c6595-dba9-4bc1-ad29-5de714f0c859.png)

**Comment by brianmiller** [comment]
My next test will be a vanilla world with just AlweStats+dependencies.  I'll report back.

All of our standard worlds have 35-80 mods loaded.  I bet another mod is causing AlweStats to throw the error.

**Comment by zAlweNy26** [comment]
Thanks for the report, I tried different ways to generate that error but nothing worked. Let me know if you find out what is causing this issue.

**Comment by zAlweNy26** [comment]
Among these mods you have in the world, are there any that significantly modify the GUI? Like Project Auga, for example.

**Comment by brianmiller** [comment]
A few and they change quite a bit.  Here's our mod list for one of our most complex worlds:

Here's the output (for one of our complex worlds) from a script we use to deploy new and patch/update existing worlds, including nested dependencies. I know BetterUI messes with the interface a lot.

 Required mods:
  EpicValheim/EpicValheim
  Amar1729/BetterLadders
  Azumatt/BetterWards
  bdew/QuickConnect
  castix/FloatingItems
  cjayride/death_tweaks_jotunn_backpacks_cjaycraft_fix
  cjayride/Discard_or_Recycle_Inventory_Items_No_Coins_cjaycraft_fix
  EmrikNorth_and_Aedenthorn/JotunnBackpacks
  GemHunter1/CustomChestName
  JereKuusela/Ore_Support
  LTmadness/BetterServerConfig
  LTmadness/FermenterPercentage
  LVH-IT/FasterTeleportation
  LVH-IT/UseEquipmentInWater
  MaGic/Quick_Deposit
  MaxiMods/MultiCraft
  Menthus/Useful_Paths
  mgway/PaddlePower
  MSchmoecker/PressurePlate
  nearbear/BiggerBoatMapExploreRadius
  nearbear/CustomSlotItemLib
  nearbear/WishboneSlot
  Nexus/FarmGrid
  Nexus/InstantMonsterLootDrop
  OdinPlus/BasementJVLedition
  OdinPlus/ChickenBoo
  OdinPlus/GoodestBoy
  OdinPlus/Heightmap_Unlimited_Remake
  OdinPlus/KnarrTheTrader
  OdinPlus/MyBuddy
  OdinPlus/OdinHorse
  OdinPlus/OdinShip
  Padank/AlweStats
  RagnarokHCRP/MoreGates
  RandyKnapp/EquipmentAndQuickSlots
  Smoothbrain/DualWield
  Smoothbrain/Lumberjacking
  swazrgb/Surtling_Boat
  TaegukGaming/aedenthornCustomAudio
  Tekla/AutoRepair
  Tekla/ColorfulSigns
  Tekla/JsonDotNet
  thedefside/BetterUI_Reforged
  TJzilla/BepInEx_ConfigurationManager
  ToastyWzrd/SwapWeaponsOnTheRun
  ValheimPlus/ValheimPlus
  denikson/BepInExPack_Valheim
  pipakin/SkillInjector
  RandyKnapp/ExtendedItemDataFramework
  ValheimModding/HookGenPatcher
  GoldenJude/Blacksmiths_tools
  ValheimModding/Jotunn
  RandyKnapp/EpicLoot
  Huntardys/EpicValheimsAdditions
  Oran1/Monsternomicon
  ASharpPen/Custom_Raids
  MonsterLabZ/MonsterLabZ
  neurodr0me/RRRMonsters
  neurodr0me/RRRNpcs
  ASharpPen/Spawn_That
  Smoothbrain/CreatureLevelAndLootControl
  AeehyehssReeper/ChaosArmor
  ASharpPen/Drop_That
  makail/Skyheim
  neurodr0me/RRRCore
  neurodr0me/RRRBetterRaids
  NexusMods/Supplemental_Raids
  abearcodes/SimpleRecycling
  NexusUploads/CustomArmorStats
  NexusUploads/RecipeCustomization
  OdinPlus/OpenDatabase
  k942/MassFarming
  RockerKitten/BoneAppetit
  Advize/PlantEverything
  AlreeNicolas/Forgotten_Biomes
  OdinPlus/Better_Trader_Remake
  Hub/VitalitySkill
  ASharpPen/This_Goes_Here
  OdinPlus/PotionPlus
  CW_Jesse/BetterNetworking_Valheim

Total Required Mods: 80

As someone that dabbles in development, I get the above list is absurd.  I'll deploy a minimum world to test AlweStats as well.

**Comment by zAlweNy26** [comment]
I will check the compatibility with some of the mods that modify the UI

**Comment by zAlweNy26** [comment]
I found an incompatibility of my enemy hud with the BetterUI one. You must disable the section in one of the mods for it to work fine. BetterUI doesn't seem to bother with the my editing mode.

**Comment by brianmiller** [comment]
Nice catch. I'll toggle them and give it a test.

Thank you!

**Comment by zAlweNy26** [comment]
Check the new patch on Thunderstore, I hope the editing mode error is fixed once for all. Let me know if you encounter this error again 😄

**Comment by zAlweNy26** [comment]
I mark this as solved, reopen it if you encounter this error again !
