### ISSUE TITLE
Error when deleting construction piece

### ISSUE THREAD

**Issue by 4Magma** [zAlweNy26/AlweStats#8]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
AlweStats.EnvStats.PatchHoveringPiece (Hud __instance) (at <34facf3403fa478c84b4bc3c152e72ac>:0)
(wrapper dynamic-method) Hud.DMD<Hud::UpdateCrosshair>(Hud,Player,single)
(wrapper dynamic-method) Hud.DMD<Hud::Update>(Hud)

removed wooden floor plates and got this error

**Comment by zAlweNy26** [comment]
You won't find this error on the new version of the mod, wait until I upload the next patch !
