### ISSUE TITLE
Suggestions/Wishes

### ISSUE THREAD

**Issue by 4Magma** [zAlweNy26/AlweStats#9]
I use some aedenthorn mods 
  Clock, Real Clock, Map Coordinates Display (and Compass)
to show infos on screen which i would replace with AlweStats

i'm interested in

- Real Time Clock:
  - in upper left corner
  - with format string
  - with seconds if possible
  - with date

 - Map Coordinates 
   -  over minimap
   - with format strings
   - default as "Player (x, y, z)\nFocus (x, y, z)"
   - if map open as "Cursor (x, y, z)"
   - if build camera used as "Camera (x, y, z)\nFocus x, y, z)"

And please add config option so i can make the background of each box 
half transparent and dark. (checkbox or as color setting)

**Comment by zAlweNy26** [comment]
What would be the point of having a clock that indicates the real time?
Anyway I like the idea of the map coordinates, so I will work to add it as soon as possible.

**Comment by 4Magma** [comment]
Why a RTC? To enable thoughts like "oh, so late, i thick i should ..."

**Comment by zAlweNy26** [comment]
Ok I understand, anyway what do you mean when you say "Focus(x, y, z)" ? About what is the focus?

**Comment by 4Magma** [comment]
Focus = Point where i look at (or as Cursor, Cross)

**Comment by zAlweNy26** [comment]
I added some of the required things and planned to add the focus coordinates as well. What do you mean by the build camera coordinates?

**Comment by 4Magma** [comment]
Build Camera 
https://www.nexusmods.com/valheim/mods/226
is a mod to move the camera freely around.
- works with hammer, hoe, cultivator, and some mod tools
- activated with hotkey, ctrl = up, shift = down

just support Focus also in case camera is moved
(i dont know if there's a difference to normal mode)

**Comment by 4Magma** [comment]
could you add configs to map coordinates 
- format string 
  - for alternive presentation like
    - "N: {z}, E: {x}, H: {y}" 
    - "{z_dir}: {z_abs}, {x_dir}: {x_abs}, H: {y}" where *_dir is replaced by N, S, E, W and 
  - sorry in case i mixed coordinates x and z up, Valheim has crashed while writing (unrelated)
 - fixed width 
   - to reduce flicker, which is "heavy" with background

question:
is it possible to create marker points around the minimap, to show 
- current direction (the little driangle is way to small)
- direction to next teleporter (optinally with distance)
- direction to next Bed (optinally with distance)

could be a simple frame with configurable size and position with icons on it

and perhaps a linear scale:
- a simple line which stands for 10^x m on map

**Comment by zAlweNy26** [comment]
> Build Camera https://www.nexusmods.com/valheim/mods/226 is a mod to move the camera freely around.
> 
> * works with hammer, hoe, cultivator, and some mod tools
> * activated with hotkey, ctrl = up, shift = down
> 
> just support Focus also in case camera is moved (i dont know if there's a difference to normal mode)

In theory I take the position of the player camera, so whether the player is in build mode or not is not relevant.

**Comment by zAlweNy26** [comment]
> could you add configs to map coordinates
> 
> * format string
>   
>   * for alternive presentation like
>     
>     * "N: {z}, E: {x}, H: {y}"
>     * "{z_dir}: {z_abs}, {x_dir}: {x_abs}, H: {y}" where *_dir is replaced by N, S, E, W and
>   * sorry in case i mixed coordinates x and z up, Valheim has crashed while writing (unrelated)
> * fixed width
>   
>   * to reduce flicker, which is "heavy" with background
> 
> question: is it possible to create marker points around the minimap, to show
> 
> * current direction (the little driangle is way to small)
> * direction to next teleporter (optinally with distance)
> * direction to next Bed (optinally with distance)
> 
> could be a simple frame with configurable size and position with icons on it
> 
> and perhaps a linear scale:
> 
> * a simple line which stands for 10^x m on map

The format string for the coordinates is already in the config file, check it out.
About the flicker, I know the problem and I hope to fix it in the next patch.
About the marker points, I think it's possible, but I don't know the best way to show them, could you please show me?
I didn't understand what you mean by the line for the linear scale. Could you show me a visual representation of what you mean?

**Comment by zAlweNy26** [comment]
Check the new patch on Thunderstore, i fixed the flicker and added other things.

**Comment by 4Magma** [comment]
Report for 3.4.0

- bow stats:
  -  isn't it to low for middle left, it's direct over HP-bar
  - suggestion: 
    - instead of "Bow ammo: {amount}/{max}\nSelected Arrows: {name}"
    - change to list of first 3 arrow types in inventory as "{amount}x {Name}", with equiped first or bolded|highlighted
- map coordinates:
  - perhaps you should not remove .0 to reduce length variation
  - is it possible to use monospaced font for the numbers?

- shouldn't map stats be visible when map is open?
  - i see all blocks like with closed map and no map stats

- the border padding was a good idea

- is it possible to get a font size setting for the infos at the cursor/cross, it's a little to small for me 

- could it be that remaining time at bushes is "00:hh:mm" instead "hh:mm:ss"? Or is this from an other mod

- for what is the position setting
  - blocks are aligned via Align
  - text in blocks is positioned by margin and padding

greetings

**Comment by zAlweNy26** [comment]
You can move each block with the config settings and also with the in game editing mode, so if you don't like the position of one block, just change it.

All the blocks are visible when they should be, anyway I like the idea of changing the font so I think I will add it in the next patch.

I also will add the font size setting in the config file for the cursor coordinates

I prefer to show the remaining time as hh:mm:ss to be more precise.

I will think about the suggestion regarding the BowStats block text and maybe I will add it.

**Comment by 4Magma** [comment]
more suggestions/wishes

could you add a sneak idicator?
- use a first person camera mod
- must go back to normal view to see if i'm sneaking
- perhaps right from game time as a symbol

reduce text in world stats:
- instead of "Days passed: {d}\nTime Played: {t} h\nCurrent Biome; {b}"
- only "{d} d\n{t} h\n{b}" or "Day {d}..."
- it should suffice to define them in description

**Comment by zAlweNy26** [comment]
I added the font size setting for the cursor coordinates, reduced the WorldStats text and added other things.
I also planned to add the custom marker points you said.
I didn't understand what you mean by the line for the linear scale. Could you show me a visual representation of what you mean? Same thing for the sneak indicator.

**Comment by 4Magma** [comment]
- https://en.wikipedia.org/wiki/Linear_scale
  - a framed line with white and black segments a 10^x m
  - e.g. minimap shows area of 450m x 450m then 4 segments each 100m
  - and the length per segment as text right from it

- sneak indicator
  - a symbol to indicate that i'm in sneak mode 
  - could be a simple block/disc in text color right from the world clock

- rotating minimap 
  - i tested a mod for this before, but didn't like it 
  - after deactivating my map remained twisted

**Comment by zAlweNy26** [comment]
You deactivated the rotating map while in game?

**Comment by 4Magma** [comment]
yes, via Configuration Manager

**Comment by zAlweNy26** [comment]
I added these two markers as elements in the status effects list.
![image](https://user-images.githubusercontent.com/41266342/159225046-b69fc756-a962-4495-bfed-48b992f248e1.png)
Check them out in the 3.6.0 patch released on ThunderStore.

**Comment by 4Magma** [comment]
Found next portal without any problems! works great.

But:
- please remove the height from distance calculation
- have a base in a OdinsUndercroft with bed and portal
- this undercrofts are always 1200m above placed 
- if standing at entrance
  - the only bed i have is in 1200m distance
  - the next portal is not these above but the other end in ~350m
- not tested but game structures are also in great height, so it might be there also weird

**Comment by zAlweNy26** [comment]
Ok I think you are right, I will fix it when the next patch is ready

**Comment by 4Magma** [comment]
could it be that your mod blocks F1 for Configuration Manager?
- i had parallel installed Server Devcommands and World Edit, but removed them because auf disturbing F1
- but after a while it came back without them

**Comment by zAlweNy26** [comment]
I didn't understand what you said, could you be more clear?

**Comment by 4Magma** [comment]
if i press F1 after a while nothing happens
but tried now to reset Orientation with backspace key for Precise Piece Placement mod and it also does nothing

i will remove alwestats for a test to see if it's the cause

**Comment by 4Magma** [comment]
it's not your mod that caused it!

**Comment by 4Magma** [comment]
I'm confused, 
- alwestats activated, server devcommands and world edit removed 
- testing for half a hour all ok, so i wrote its not your mod
- but after another 20min of playing:
  - this keys doesn't work anymore
    - F1 for Configuration Manager 
    - j to toggle Safe Zone mod (shows circles around no spawn areas)
    - b to toggle Build Camera
    - all keys for Precise Piece Placement (keyboard and mouse)
  - while this keys work normal
    - vanilla keys like F5, r, t
    - F8 for Alwestats edit mode 
    - Here Fishy hotkey
    - Equipment and Slots' food slot hotkeys 
    - Building Repair hotkey (u)
    - Hoe Radius hotkey (alt)
- and smart Containers seems to top to work

**Comment by zAlweNy26** [comment]
I don't manage with input keys in that way, just for the editing mode. So I think that probably isn't my mod that is causing this bug.

**Comment by 4Magma** [comment]
I don't know, 
- only this 3 mods was added/updated today
- the other two dll are removed
- try with alwestat 3.5 to see if bug comes back after some time

**Comment by 4Magma** [comment]
Found the problem, i hope
- downloaded yesterday new OdinsUndercroft version 1.1.6
- installed it along the 3 mods in case i haven't already yesterday
- make a new test, with previous version,
- OU is not the first time the cause for something

**Comment by 4Magma** [comment]
i think was an outside of valheim problem
- couldn't close mixed reality and windows update page was empty

sorry for the trouble

**Comment by zAlweNy26** [comment]
No problem !

**Comment by 4Magma** [comment]
new suggestions:

- entities:
  - can you add the distance info for archery
  - can you make the HP% optional or move it, because it reduced the recognizability of the health bar

- direction arrows
  - i think one for ships is also often needed

- rotating minimap:
  - said that i didn't like it (because i lose orientation)
  - suggestions to make it less confusing 
    - place big N,E,S,W around or
    - make a bold line on the north side or
    - make map bigger, round, and give it a compass look

**Comment by zAlweNy26** [comment]
What do you mean with distance info for archery? Do you mean the distance between the player and the entity? And if yes, where should it be displayed?

In the next patch, there will be a direction arrow even for the closer ship.

I like a bit the idea for the rotating minimap, I'll think about how to implement it in the better way I know.

**Comment by 4Magma** [comment]
> What do you mean with distance info for archery? Do you mean the distance between the player and the entity? And if yes, where should it be displayed?
- exactly 
- perhaps as " (... m)" behind the name or under the health bar
- optinally only for the nearest to the cross hair

is it possible to use an other color fpr the health bar for tamed 
and timid (deer) entities?

**Comment by zAlweNy26** [comment]
Ok, thanks for the explanation.
Anyway yes, it is possible, which colors do you suggest?

**Comment by 4Magma** [comment]
- green would be logical, but worse against most biome
- so yellow, orange or something more not biome-like cyan, magenta
- and make it a config, make it the problem of the user

**Comment by zAlweNy26** [comment]
Check the new features I added and let me know if you encounter any issues !

**Comment by 4Magma** [comment]
> You can change the color of the health bar for tamed animals
- works
- possible to add deer?
- how about as color groups (each inputs: list of entities and color)
  - e.g.: tamed+timid, normal, aggressive (default)
  - i don't need it, but perhaps other

> Added player stats when choosing the character (kills, deaths, crafts, builds)
- ok

> Fixed world days text in world selection panel not showing when changing tab
- with tab ok
- but with up/down keys it vanished 

> Fixed position of closer portal element showing too much spaced from others status effects when a bed wasn't claimed


> Added direction and distance from closer ship as element in the status effect list
- ok

>    Now the distance calculation for closer portal, closer ship and claimed bed ignores the height
- ok

> You can see the distance between you and the entity you are hovering, below the health bar
- works, but its not as useful as i hoped for
  - to trigger it the entity can't be far away
    - could you add an option to make it for all health bars
	  - i use third eye mod (former Creature sense) to trigger all health bars in my surrounding
	- or find a way to trigger it for more distant entities
  - to use it for archery, i think it should be in form of 
    - "{horizontal_distance} m, {vertical_distance} m {up|down_arrow}"

>    Toggle pins for portals, ships, carts and dungeons (troll caves, crypts and fire holes)
- i use already Auto Map Pins, so for most objects i have already pins on map
- portal icon doesn't change size while zooming in/out map
- icon for crypts and troll caves are to small (if i used them)


> Toggle the title for the custom pins
- ?

> You can set the scale of the player marker icon
- useful

> You can choose to double or not the size of the custom pins
- ignored (because of Auto Map Pins)

is it possible to create a direction arrow from a ping placed on map?
- automatical deactivate if in range of 5-10m from target

**Comment by 4Magma** [comment]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Plant.TimeSincePlanted () (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
AlweStats.EnvStats.PatchPlantHoverText (System.String __result, Plant __instance) (at <b5f63675929b4f51a10f3d4156c8f67b>:0)
(wrapper dynamic-method) Plant.DMD<Plant::GetHoverText>(Plant)
AlweStats.EnvStats.OnDamage (Destructible __instance, HitData hit) (at <b5f63675929b4f51a10f3d4156c8f67b>:0)
(wrapper dynamic-method) Destructible.DMD<Destructible::RPC_Damage>(Destructible,long,HitData)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Delegate.DynamicInvokeImpl (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Delegate.DynamicInvoke (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
RoutedMethod`1[T].Invoke (System.Int64 rpc, ZPackage pkg) (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
ZNetView.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData rpcData) (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
ZRoutedRpc.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData data) (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
ZRoutedRpc.InvokeRoutedRPC (System.Int64 targetPeerID, ZDOID targetZDO, System.String methodName, System.Object[] parameters) (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
ZNetView.InvokeRPC (System.String method, System.Object[] parameters) (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
(wrapper dynamic-method) Destructible.DMD<Destructible::Damage>(Destructible,HitData)
(wrapper dynamic-method) Attack.DMD<Attack::DoMeleeAttack>(Attack)
Attack.OnAttackTrigger () (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
Humanoid.OnAttackTrigger () (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
CharacterAnimEvent.Hit () (at <dcb0de0155834d459f18d7ac6ea5244b>:0)

**Comment by zAlweNy26** [comment]
When does this error occur?

**Comment by 4Magma** [comment]
not sure, 
- saw it in log while chopping multiple birches
- only 1 error in this time, so i don't think is related to it
- was near a base with carrots and red berries

**Comment by 4Magma** [comment]
Possible Error/Bug:
- i'm currently reconstructing my base and are over long time in build mode and build camera mode
- thereby i noticed that plants show 100% but don't change to full grown version
- they have harvest option, but nothing happen when i pressed E
- teleport away changes nothing, but after relogin they change shortly after

**Comment by zAlweNy26** [comment]
I know but it seems to be a bug of the game, my mod just shows the remaining time and percentage, I don't affect in any way the growth process of the plants.

**Comment by zAlweNy26** [comment]
I close this issue because I added all the suggestions I liked, feel free to open it again if you have any other suggestions.
